base/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from base.decorators import has_permission
from base.views.business import BusinessRegister, BusinessProfile
#from easy_pdf.views import PDFTemplateView
from base.views.customer_view import CustomerView, CustomeRegisterView, CustomerRemoveView, CustomerEditView, \
    CustomerSelectView
from base.views.dashboard_view import Dashboard
from base.views.invoice import ProposalEvent, ProposalItemsView, ProposalView, ItemView, ItemDelete, ProposalAccept, \
    ProposalDeny, ProposalEmailSend, InvoiceView, InvoiceEvent, InvoiceEmailSend, \
    ProposalDeleteView, InvoiceDeleteView, invoice_downloadpdf, proposal_downloadpdf
from base.views.stripe_views import StripeAuthorizeView, StripeCallbackView, StripeSubscribeView, InvoiceCharge

urlpatterns = [

    url(r'^customers/$', login_required(CustomerView.as_view()), name="customers"),
    url(r'^customers/(?P<id>\d+)/$', login_required(CustomerView.as_view()), name="customer"),
    url(r'^customers/add$', login_required(CustomeRegisterView.as_view()), name="add_customer"),
    url(r'^customers/delete/(?P<id>\d+)/$', login_required(CustomerRemoveView.as_view()), name="delete_customer"),
    url(r'^customers/edit/(?P<id>\d+)/$', login_required(CustomerEditView.as_view()), name="edit_customer"),
    url(r'^customers/list/$', login_required(CustomerSelectView.as_view()), name="customer_list"),
    url(r'^business/register$', BusinessRegister.as_view(), name="business_register"),
    url(r'^business/profile/$', login_required(BusinessProfile.as_view()), name="business_profile"),
    # url(r'^business/subscription/payment/$', login_required(PaymentOrder.as_view()), name="payment_subs"),
    url(r'^proposal/$', login_required(ProposalView.as_view()), name="proposal_list"),
    url(r'^proposal/event/$', login_required(ProposalEvent.as_view()), name="proposal_event_create"),
    url(r'^proposal/(?P<id>\d+)/event/$', login_required(ProposalEvent.as_view()), name="proposal_event_edit"),
    url(r'^proposal/(?P<id>\d+)/items/$', login_required(ProposalItemsView.as_view()), name="proposal_items_step"),
    url(r'^proposal/(?P<id>\d+)/items/list/$', login_required(ItemView.as_view()), name="proposal_items"),
    url(r'^proposal/(?P<id>\d+)/items/(?P<id_item>\d+)/$', login_required(ItemView.as_view()), name="proposal_item_edit"),
    url(r'^proposal/(?P<id>\d+)/items/(?P<id_item>\d+)/delete/$', login_required(ItemDelete.as_view()), name="proposal_item_delete"),
    url(r'^proposal/(?P<id>\d+)/$', login_required(ProposalView.as_view()), name="proposal_detalles"),
    url(r'^proposal/send/(?P<id>\d+)/$', login_required(ProposalEmailSend.as_view()), name="proposal_send"),
    url(r'^proposal/accept/(?P<pidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', ProposalAccept.as_view(), name="accept_proposal"),
    url(r'^proposal/deny/(?P<pidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', ProposalDeny.as_view(), name="deny_proposal"),
    url(r'^proposal/accept/(?P<id>\d+)/$', login_required(ProposalAccept.as_view()), name="accept_proposal_sys"),
    url(r'^proposal/deny/(?P<id>\d+)/$',( ProposalDeny.as_view()), name="deny_proposal_sys"),
    url(r'^proposal/delete/(?P<id>\d+)/$',( ProposalDeleteView.as_view()), name="delete_proposal"),
    url(r'^proposal/download/(?P<id_proposal>\d+)/$', login_required(proposal_downloadpdf), name="proposal_download"),

    url(r'^invoice/$', login_required(InvoiceView.as_view()), name="invoice_list"),
    url(r'^invoice/event/$', login_required(InvoiceEvent.as_view()), name="invoice_event_create"),

    url(r'^invoice/(?P<id>\d+)/event/$', login_required(InvoiceEvent.as_view()), name="invoice_event_edit"),
    url(r'^invoice/(?P<id>\d+)/$', login_required(InvoiceView.as_view()), name="invoice_detalles"),
    url(r'^invoice/(?P<id_invoice>\d+)/items/$', login_required(ProposalItemsView.as_view()), name="invoice_items_step"),
    url(r'^invoice/send/(?P<id>\d+)/$', login_required(InvoiceEmailSend.as_view()), name="invoice_send"),
    url(r'^invoice/download/(?P<id_invoice>\d+)/$', login_required(invoice_downloadpdf), name="invoice_download"),
    # url(r'^invoice/accept/(?P<iidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', InvoiceAccept.as_view(), name="accept_invoice"),
    # url(r'^invoice/cancel/(?P<iidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', InvoiceCancell.as_view(), name="cancel_invoice"),
    url(r'^invoice/delete/(?P<id>\d+)/$',(InvoiceDeleteView.as_view()), name="delete_invoice"),

    url(r'^business/stripe/authorize/(?P<business_id>\d+)/$', StripeAuthorizeView.as_view(), name='connect_stripe'),
    url(r'^business/stripe/callback/$', StripeCallbackView.as_view(), name='stripe_callback'),
    url(r'^business/stripe/subscribe/(?P<business_id>\d+)/$', StripeSubscribeView.as_view(), name='stripe_subscribe'),
    url(r'^business/stripe/invoice/charge/(?P<iidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', InvoiceCharge.as_view(), name='stripe_invoice_charge'),

    #url(r'^pdf/$', PDFTemplateView.as_view(template_name='pdf.html',
    #                                           filename='my_pdf.pdf'), name='proposal_list_pdf'),

    # url(r'^proposal/pdf/$',(PrintPDF.as_view()), name="print_pdf"),

    # url(r'^pdf/$', genpdf, name='pdf'),
]

caterfull/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout_then_login, password_reset_done, password_reset_complete

from base.views.account import password_change_done, ConfirmEmailView, password_change, password_reset, password_reset_confirm
from base.views.dashboard_view import Dashboard

urlpatterns = [
                  url(r'^$', login_required(Dashboard), name="dashboard"),
                  url(r'^admin/', admin.site.urls),
                  # url(r'^accounts/login/$', login, {'template_name': 'base/login.html','authentication_form':CaterAuthenticationForm}, name='login'),
                  url(r'^accounts/login/$', login, {'template_name': 'base/login.html'}, name='login'),
                  url(r'^accounts/logout/$', logout_then_login, name="logout"),
                  # url(r'^accounts/password_reset/$', password_reset,{'template_name':'base/password_reset.html'}, name='password_reset'),
                  url(r'^accounts/password_reset/$', password_reset, name='password_reset'),
                  # url(r'^accounts/password_change/$', password_change,{'template_name':'base/password_change.html'}, name="password_change"),
                  url(r'^accounts/password_change/$', password_change, name="password_change"),
                  url(r'^accounts/password_change/done/$', password_change_done, name="password_change_done"),
                  url(r'^accounts/password_reset/done/', password_reset_done,
                      {'template_name': 'base/password_reset_done.html'}, name="password_reset_done"),
                  # url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name':'base/password_reset_confirm.html'}, name="password_reset_confirm"),
                  url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      password_reset_confirm, name="password_reset_confirm"),
                  url(r'^accounts/reset/done/', password_reset_complete,
                      {'template_name': 'base/password_reset_complete.html'}, name="password_reset_complete"),
                  url(
                      r'^accounts/registration_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      ConfirmEmailView.as_view(), name="registration_confirm"),
                  # url('^',include('django.contrib.auth.urls')),
                  url(r'^stripe/', include('stripe_cater.urls')),
                  url(r'^site/', include('business_site.urls')),
                  url(r'^', include('base.urls'))
              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# url(r'^password_change/$', views.password_change, name='password_change'),
#    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
#    url(r'^password_reset/$', views.password_reset, name='password_reset'),
#    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
#    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
#        views.password_reset_confirm, name='password_reset_confirm'),
#    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),

base/forms.py
from datetime import datetime

from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.forms.forms import Form
from django.forms.models import ModelForm, ModelChoiceField
from django.forms.widgets import Textarea, PasswordInput

from base.model_invoice import Event
from base.models import Customer, Business


# widgets
class SubscriptionModelChoiceField(ModelChoiceField):

    def label_from_instance(self, obj):
        return obj.description

# forms

class CustomerForm(ModelForm):

    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    comments = forms.CharField(max_length=250, widget=Textarea, required=False)
    company = forms.CharField(max_length=50, required=False)

    class Meta:
        model = Customer
        fields = ['suffix','prefix']

class BusinessForm(Form):

    phone = forms.CharField(max_length=20, error_messages={'required':'Campo Requerido'},widget=forms.TextInput(attrs={'placeholder':"Phone"}))
    name = forms.CharField(max_length=250,widget=forms.TextInput(attrs={'placeholder':"Business name"}))
    first_name = forms.CharField(max_length=25,widget=forms.TextInput(attrs={'placeholder':"First name"}))
    last_name = forms.CharField(max_length=25,widget=forms.TextInput(attrs={'placeholder':"Last name"}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':"Password"}), max_length=25)
    password_confirm = forms.CharField(widget=PasswordInput(attrs={'placeholder':"Password confirm"}), max_length=25)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':"Email"}))
    address = forms.CharField(max_length=250,widget=forms.TextInput(attrs={'placeholder':"Address"}))
    #subscriptions = SubscriptionModelChoiceField(queryset=SubscriptionType.objects.all(), widget=RadioSelect, empty_label=None, to_field_name="id")
    tax = forms.DecimalField(max_digits=5, decimal_places=3, min_value=0,widget=forms.NumberInput(attrs={'placeholder':"Tax"}))



    def clean_password_confirm(self):
            if self.data['password'] != '' and self.data['password'] != self.data['password_confirm']:
                raise forms.ValidationError('La contraseña y su confirmación no coinciden.')
            return self.data['password_confirm']

class BusinessProfileForm(Form):

    phone = forms.CharField(max_length=20, error_messages={'required':'Campo Requerido'})
    name = forms.CharField(max_length=250)
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    email = forms.EmailField()
    address = forms.CharField(max_length=250, widget=forms.Textarea())
    tax = forms.DecimalField(max_digits=5, decimal_places=3, min_value=0)
    logo = forms.FileField(required=False)

# class CaterAuthenticationForm(AuthenticationForm):
#
#     def confirm_login_allowed(self, user):
#
#         AuthenticationForm.confirm_login_allowed(self, user)
#
#         subs_disable_message = "Su suscripcion vigente no esta activada o ha expirado."
#
#         groups = user.groups.all()
#         if(len(groups)) and groups.first().name in settings.BUSINESS_GROUPS:
#             b = Business.objects.filter(owner=user).first()
#             sub = b.subscription_set.filter(current=True).first()
#             if sub.expire_date < datetime.date(datetime.today()) or not sub.is_active():
#
#                 raise forms.ValidationError(
#                 subs_disable_message,
#                 code='invalid_subscription',
#                 # params={'username': self.username_field.verbose_name},
#             )

    # def clean(self):
    #
    #     subs_disable_message = "Su suscripcion vigente no esta activada o ha expirado."
    #
    #     cleaned_data = AuthenticationForm.clean(self)
    #
    #     if cleaned_data.get('username'):
    #         user = User.objects.filter(email=cleaned_data.get('username')).first()
    #
    #         groups = user.groups.all()
    #         if(len(groups)) and groups.first().name in settings.BUSINESS_GROUPS:
    #             b = Business.objects.filter(owner=user).first()
    #             sub = b.subscription_set.filter(current=True).first()
    #             if sub.expire_date > datetime.date(datetime.today()) and sub.active:
    #                 return cleaned_data
    #             else:
    #                 raise forms.ValidationError(
    #                 subs_disable_message,
    #                 code='invalid_subscription',
    #                 # params={'username': self.username_field.verbose_name},
    #             )
    #         else:
    #             return cleaned_data
    #
    #     return cleaned_data

# class CustomerModelChoice(ModelChoiceField):
#
#     def __init__(self,queryset, initial=None,*args, **kwargs):
#         print('hola')
#         print(initial)
#         super(CustomerModelChoice, self).__init__(queryset,initial=initial, *args, **kwargs)




class PasswordReset(PasswordResetForm):

    def clean_email(self):
        user = User.objects.filter(email=self.data['email']).filter(is_active=True).first()
        if not user:
            raise forms.ValidationError('Email Invalido')
        return self.data['email']

class EventForm(forms.ModelForm):
    name = forms.CharField(max_length=25)
    address = forms.CharField(max_length=150)
    event_date = forms.DateField()
    customer = forms.ModelChoiceField(queryset=Customer.objects.all())



    def __init__(self,*args, **kwargs):
        print(kwargs)
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['customer'].queryset = Customer.objects.filter(business=kwargs.get('initial').get('business'))

    class Meta:
        model = Event
        exclude = ['due_date']

class ProposalEventForm(EventForm):
    due_date = forms.DateField()
    comment = forms.CharField(widget=forms.Textarea(), max_length=150, required=False)

    def clean_event_date(self):
        print(self.data['event_date'])
        print(self.fields['event_date'].to_python((self.data['event_date'])))
        print(datetime.today().timestamp())
        if self.fields['event_date'].to_python((self.data['event_date'])) < datetime.today().date():
            raise forms.ValidationError('La fecha del evento debe ser posterior al fecha actual')
        return  self.data['event_date']

    def clean_due_date(self):
        due_date = self.fields['due_date'].to_python((self.data['due_date']))
        event_date = self.fields['event_date'].to_python((self.data['event_date']))
        if due_date < event_date:
            raise forms.ValidationError('La fecha de pago debe ser posterior a la fecha del evento')
        return self.data['due_date']


class ItemForm(forms.Form):

    description = forms.CharField(max_length=150, widget=forms.Textarea())
    quantity = forms.IntegerField(min_value=0)
    discount = forms.DecimalField(max_digits=4, decimal_places=2, initial=0, min_value=0)
    unit_cost = forms.DecimalField(max_digits=9, decimal_places=2, min_value=0)
    oferta = forms.CharField(max_length=50)

base/views/dashboard_view.py
from django.shortcuts import render

__author__ = 'Hector'

def Dashboard(request):
    context = {}
    #context = {'available_languages': ['en', 'es', 'fr']}
    return render(request,'base/dashboard.html', context)

# def genpdf(request):
#     resp = HttpResponse(content_type='application/pdf')
#     result = generate_pdf('pdf.html', file_object=resp)
#     return result

base/templates/base/invoice/wizard/event_step.html
{% load widget_tweaks %}
{% load staticfiles %}
{% load i18n admin_static %}


<form method="post" action="" name="eventForm" id="eventForm" class="form-horizontal" novalidate="novalidate">
    {% csrf_token %}

    <div class="form-group {% if form.name.errors %} has-error {% endif %}">
        <label class="control-label col-xs-12 col-sm-3 no-padding-right">Nombre</label>

        <div class="col-xs-12 col-sm-4">
            <div class="clearfix">
                {% render_field form.name class="form-control" %}
            </div>
            {% for error in  form.name.errors %}
                <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
            {% endfor %}

        </div>
    </div>

    <div class="form-group {% if form.address.errors %} has-error {% endif %}">
        <label class="control-label col-xs-12 col-sm-3 no-padding-right">Dirección</label>

        <div class="col-xs-12 col-sm-6">
            <div class="clearfix">
                {% render_field form.address class="form-control" %}
            </div>
            {% for error in  form.address.errors %}
                <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
            {% endfor %}
        </div>
    </div>

    <div class="form-group {% if form.event_date.errors %} has-error {% endif %}">
        <label class="control-label col-xs-12 col-sm-3 no-padding-right">Dia</label>

        <div class="col-xs-12 col-sm-2">
            <div class="input-group ">
                {% render_field form.event_date class="form-control date-picker" %}
             <span class="input-group-btn">
                        <button class="btn btn-flat btn-default" type="button">
                            <i class="ace-icon fa fa-calendar "></i>
                        </button>
                    </span>
            </div>

            {% for error in  form.event_date.errors %}
                <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
            {% endfor %}
        </div>
    </div>


    <div class="form-group {% if form.due_date.errors %} has-error {% endif %}">
        <label class="control-label col-xs-12 col-sm-3 no-padding-right">Dia de pago</label>

        <div class="col-xs-12 col-sm-2">
            <div class="input-group">
                {% render_field form.due_date class="form-control date-picker" %}
                  <span class="input-group-btn">
                        <button class="btn btn-flat btn-default"
                                type="button">
                            <i class="ace-icon fa fa-calendar "></i>

                        </button>
                    </span>
            </div>
            {% for error in  form.due_date.errors %}
                <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
            {% endfor %}
        </div>
    </div>
    <div class="hr hr-dotted"></div>
    <div class="form-group {% if form.customer.errors %} has-error {% endif %}">
        <label class="control-label col-xs-12 col-sm-3 no-padding-right">Cliente</label>

        <div class="col-xs-11 col-sm-2" id="selectContainer">
            <div class="clearfix">
                {% render_field form.customer class="form-control chosen-select" %}
            </div>
            {% for error in  form.customer.errors %}
                <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
            {% endfor %}
        </div>
        <button id="add_client" class="btn btn-success btn-flat add" style="margin-left: -15px"
                data-toggle="modal"
                data-target="#newCustomerModal"
                data-modal-title="Nuevo contacto" type="button"><i class="fa fa-plus"></i></button>
    </div>

    <div class="form-group {% if form.comment.errors %} has-error {% endif %}">
        <label class="control-label col-xs-12 col-sm-3 no-padding-right">Comentario</label>

        <div class="col-xs-12 col-sm-4">
            <div class="clearfix">
                {% render_field form.comment class="form-control" %}
            </div>
            {% for error in  form.comment.errors %}
                <div class="text-validation-error"><i class="fa fa-warning"></i> {% trans error %} </div>
            {% endfor %}
        </div>
    </div>


</form>
<script>

    $(document).ready(function () {
//datepicker plugin
        //link
        $('.date-picker').datepicker({
            autoclose: true,
            todayHighlight: true,
            format: 'yyyy-mm-dd',
            startDate: "dateToday",
            language: "es"
        })
            //show datepicker when clicking on the icon
                .next().on('click', function () {
                    $(this).prev().focus();
                });
        {#        $("#id_event_date").change(function () {#}
        {#            $("#id_due_date").datepicker({#}
        {#                startDate: $("#id_event_date").val()#}
        {#            })#}
        {#        })#}

        /*Select*/
        $('.chosen-select').chosen({allow_single_deselect: true});
        //resize the chosen on window resize

        $(window)
                .off('resize.chosen')
                .on('resize.chosen',function () {
                    $('.chosen-select').each(function () {
                        var $this = $(this);
                        $this.next().css({'width': $this.parent().width()});
                    })
                }).trigger('resize.chosen');


        $.CustomDatatableFormObject.model_name = "customers";

        $.CustomDatatableFormObject.modal_dialog_id = "#newCustomerModal";
        $.CustomDatatableFormObject.form_id = "#newCustomerForm";
        $.CustomDatatableFormObject.has_fn_callback = true;
        $.CustomDatatableFormObject.fn_callback = function () {
            var url = '/customers/list';

            $.get(url, {id: this.model_id}, function (data) {
                $('#selectContainer').empty().append(data);
            });

        };

        $model_name = 'proposal';

    });
</script>
{% include 'base/includes/modalFormCusomer.html' %}

<script src="{% static 'base/js/invoice/item.js' %}"></script>

base/templates/base/invoice/wizard/event_step_amado.html
{% load widget_tweaks %}
{% load staticfiles %}
<form method="post">
    {% csrf_token %}
    <div>
        Nombre {% render_field form.name %}
        <div>{{ form.name.errors }}</div>
    </div>

    <div>
        Direccion {% render_field form.address %}
        <div>{{ form.address.errors }}</div>
    </div>
    <div>
        Dia{% render_field form.event_date %}
        <div>{{ form.event_date.errors }}</div>
    </div>
    <div>
        Dia de pago {% render_field form.due_date %}
        <div>{{ form.due_date.errors }}</div>
    </div>
    <div id="customer_field">
        Cliente {% render_field form.customer %}
        <div>{{ form.customer.errors }}</div>
    </div>
    <div>
        Comentario {% render_field form.comment %}
        <div>{{ form.comment.errors }}</div>
    </div>
    <div style="border-width: medium">
        <fieldset id="customer-form">

        </fieldset>
        <button id="add_client" data-url="{% url 'customer_list' %}" hidden>Guardar</button>
        <button id="load_client_form" data-url="{% url 'add_customer' %}">Cliente Nuevo</button>
    </div>
    <input type="submit" value="Save"/>

    <div>
        {{ errors }}
    </div>
</form>

<script type="text/javascript" src="{% static 'base/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/invoice/event.js' %}"></script>

base/templates/base/invoice/wizard/item_add_step.html
{% load staticfiles %}
<script src="{% static 'js/jquery.js' %}"></script>
<button id="add_item" class="btn btn-success pull-right add"
        data-toggle="modal"
        data-target="#itemModal"
        data-modal-title="Nuevo item"><i class="fa fa-plus"></i> Agregar Item
</button>
<div class="clearfix"></div>
<div id="items_container" data-url-load="{% url 'proposal_items' proposal.id %}">
    {% include 'base/invoice/includes/items.html' with items=proposal.get_items %}
</div>
<input type="hidden" id="model_name" value="{{ model }}"/>
{#<div id="form_container" hidden>#}
{#    {% include 'base/invoice/includes/item_form.html' %}#}
{#</div>#}


<script>
    $(document).ready(function () {

        $.CustomDatatableFormObject = {

            model_name: "",
            model_id: -1,
            get_url_base: function () {
                return "/" + this.model_name + "/"
            },
            get_url_add: function () {
                if (this.add == '')
                    return "/" + this.model_name + "/add"
                return "/" + this.model_name + "/" + this.add;
            },
            get_url_edit: function () {
                if (this.edit == '')
                    return "/" + this.model_name + "/edit/" + this.model_id + "/";
                return "/" + this.model_name + "/" + this.edit + "/" + this.model_id + "/";

            },
            get_url_delete: function () {
                return "/" + this.model_name + "/delete/" + this.model_id + "/"
            },
            set_url_add: function (url) {
                this.add = url;
            },
            set_url_edit: function (url) {
                this.edit = url;
            },
            datatable_container: "",
            datatable_id: "",
            modal_dialog_id: "",
            form_id: "",
            add: "",
            edit: "",
            fn_callback: "",
            has_fn_callback: ""

        };

        $.CustomDatatableFormObject.modal_dialog_id = "#itemModal";
        $.CustomDatatableFormObject.model_name = $("#model_name").val();
        //$.CustomDatatableFormObject.datatable_container = "#tableContainer";
        //$.CustomDatatableFormObject.datatable_id = "#customers_table";
        $.CustomDatatableFormObject.form_id = "#item_form";

    });

</script>
<script src="{% static 'base/js/invoice/item_form.js' %}"></script>
{% include 'base/includes/modalFormItems.html' %}